name: run run.py

on:
  schedule:
    - cron: '0 0 * * *' # At 12:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python run.py
          
      - name: commit files
        run: |
          git config --local user.email "changehere@github.com"
          git config --local user.name "changehere"
          git add -A
          git commit -a -m "updated logs" --allow-empty
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
          force: true
          tags: true
